version: "3.8"

services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: mykitchen_hub_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - test-network

  mykitchen-hub-test:
    build: .
    environment:
      - DB_URL=jdbc:mysql://mysql-test:3306/mykitchen_hub_test
      - DB_USERNAME=testuser
      - DB_PASSWORD=testpassword
      - JWT_SECRET=test-secret-key-for-testing-purposes-only
      - JWT_EXPIRATION=86400000
      - JWT_REFRESH_EXPIRATION=604800000
      - EMAIL=test@example.com
      - EMAIL_PASSWORD=testpassword
      - CLOUDINARY_CLOUD_NAME=test
      - CLOUDINARY_API_KEY=test
      - CLOUDINARY_API_SECRET=test
      - SERVER_PORT=8080
    ports:
      - "8081:8080"
    depends_on:
      mysql-test:
        condition: service_healthy
    networks:
      - test-network
    command: ["./mvnw", "test", "-Dspring.profiles.active=test"]

networks:
  test-network:
    driver: bridge
